# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tiro.speech.v1alpha import speech_pb2 as tiro_dot_speech_dot_v1alpha_dot_speech__pb2


class SpeechStub(object):
    """Service that implements Google Cloud Speech API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.unary_unary(
                '/tiro.speech.v1alpha.Speech/Recognize',
                request_serializer=tiro_dot_speech_dot_v1alpha_dot_speech__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=tiro_dot_speech_dot_v1alpha_dot_speech__pb2.RecognizeResponse.FromString,
                )
        self.StreamingRecognize = channel.stream_stream(
                '/tiro.speech.v1alpha.Speech/StreamingRecognize',
                request_serializer=tiro_dot_speech_dot_v1alpha_dot_speech__pb2.StreamingRecognizeRequest.SerializeToString,
                response_deserializer=tiro_dot_speech_dot_v1alpha_dot_speech__pb2.StreamingRecognizeResponse.FromString,
                )


class SpeechServicer(object):
    """Service that implements Google Cloud Speech API.
    """

    def Recognize(self, request, context):
        """Performs synchronous speech recognition: receive results after all audio
        has been sent and processed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingRecognize(self, request_iterator, context):
        """Performs bidirectional streaming speech recognition: receive results while
        sending audio. This method is only available via the gRPC API (not REST).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=tiro_dot_speech_dot_v1alpha_dot_speech__pb2.RecognizeRequest.FromString,
                    response_serializer=tiro_dot_speech_dot_v1alpha_dot_speech__pb2.RecognizeResponse.SerializeToString,
            ),
            'StreamingRecognize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingRecognize,
                    request_deserializer=tiro_dot_speech_dot_v1alpha_dot_speech__pb2.StreamingRecognizeRequest.FromString,
                    response_serializer=tiro_dot_speech_dot_v1alpha_dot_speech__pb2.StreamingRecognizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tiro.speech.v1alpha.Speech', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Speech(object):
    """Service that implements Google Cloud Speech API.
    """

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tiro.speech.v1alpha.Speech/Recognize',
            tiro_dot_speech_dot_v1alpha_dot_speech__pb2.RecognizeRequest.SerializeToString,
            tiro_dot_speech_dot_v1alpha_dot_speech__pb2.RecognizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamingRecognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/tiro.speech.v1alpha.Speech/StreamingRecognize',
            tiro_dot_speech_dot_v1alpha_dot_speech__pb2.StreamingRecognizeRequest.SerializeToString,
            tiro_dot_speech_dot_v1alpha_dot_speech__pb2.StreamingRecognizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
